on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npm ci
      - run: npm run generate
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Set up Maven Central Repository
        if: steps.changes.outputs.changed == 1
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'
      - name: Build with Maven
        if: steps.changes.outputs.changed == 1
        run: ./mvnw clean verify --no-transfer-progress
      - uses: EndBug/add-and-commit@v9
        if: steps.changes.outputs.changed == 1
        with:
          default_author: github_actions
          message: "fix: Regenerate types"
